service: google-token-api

provider:
  name: aws
  runtime: python3.11
  region: us-east-1
  environment:
    API_KEY: ${env:API_KEY}

functions:
  app:
    handler: wsgi.handler
    events:
      - http:
          path: /{proxy+}
          method: any
          cors: true

plugins:
  - serverless-wsgi
  - serverless-python-requirements

custom:
  wsgi:
    app: wsgi.handler
    packRequirements: false

  pythonRequirements:
    dockerizePip: true
